name: TracerBlocker
main: cz.GravelCZLP.TracerBlocker.TracerBlocker
version: 3.0.0
authors: [kukelekuuk00, GravelCZLP]
depend: [ProtocolLib, PacketWrapper]
commands:
  tracerblocker:
    aliasses: [antitracer,tracer, antiesp, antiplayeresp, antichestesp]