name: TracerBlocker
main: cz.GravelCZLP.TracerBlocker.TracerBlocker
version: 2.0.1
authors: [kukelekuuk00, GravelCZLP]
depend: [ProtocolLib, PacketWrapper]
commands:
  tracerblocker:
    aliasses: [antitracer,tracer, antiesp, antiplayeresp, antichestesp]