name: TracerBlocker
main: cz.GravelCZLP.TracerBlocker.TracerBlocker
version: BETA-2.0.0-PRE
authors: [kukelekuuk00, GravelCZLP]
depend: [ProtocolLib]
commands:
  tracerblocker:
    aliasses: [antitracer,tracer, antiesp, antiplayeresp, antichestesp]
